# Generated by Django 3.2.6 on 2021-09-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mama_cas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxygrantingticket',
            name='login_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='ip'),
        ),
        migrations.AddField(
            model_name='proxygrantingticket',
            name='username',
            field=models.CharField(blank=True, max_length=255, verbose_name='username'),
        ),
        migrations.AddField(
            model_name='proxyticket',
            name='login_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='ip'),
        ),
        migrations.AddField(
            model_name='proxyticket',
            name='username',
            field=models.CharField(blank=True, max_length=255, verbose_name='username'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='login_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='ip'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='username',
            field=models.CharField(blank=True, max_length=255, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='proxygrantingticket',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='proxyticket',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
